import type { DashboardPatient, DashboardStats, Doctor } from "@/types";

export const mockDoctor: Doctor = {
  id: "1",
  name: "Dr. Sarah Cole",
  role: "Obstetrics Lead",
  email: "sarah.cole@mamaguard.health",
  avatarUrl:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuCxCDxcYwS-hwhZFelLIn7JgaDkZXfSVjO-Cng4HBNLPywrWaVXxkgg7wymY81ZdxaazEh-eC5vsLCKOXNkmUP6_-On-vCfkHAsBrp6GBkYLpVtdNV6D0kGQwhcOIyNLAHxlFZ2JVT2AxAHvJMFW4iv9InrWDlAsHV3TqyoyVgPpsr7zdU4Xgha6smI1McZ1CMcpN2sIM4oby82xGp1y6Yet12ijPJIJySl80VGKOOXVftQSrpopCV3EgBnQAuTNZEv26vD-O9ErH0i",
};

export const mockStats: DashboardStats = {
  critical: 4,
  warning: 12,
  stable: 142,
};

export const mockCriticalPatients: DashboardPatient[] = [
  {
    id: "1",
    phone_number: "+254700000001",
    full_name: "Sarah Jenkins",
    name: "Sarah Jenkins",
    due_date: "2026-04-15",
    gestational_week: 32,
    risk_level: "critical",
    language: "en",
    medical_history: { notes: "Previous preeclampsia" },
    created_at: "2025-08-15T00:00:00Z",
    date_of_birth: "1992-03-10",
    national_id: null,
    location_address: "Nairobi, Kenya",
    trimester: 3,
    blood_type: "O+",
    previous_pregnancies: 1,
    current_medications: null,
    allergies: null,
    emergency_contact_name: "John Jenkins",
    emergency_contact_relation: "Husband",
    emergency_contact_phone: "+254700000002",
    preferred_checkup_time: "morning",
    has_smartphone: true,
    avatarUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDOD_FtHE_M2MnQU5X4ENnkwxe6hDrAzl0WEzGP3ROfYIX4RTvu05KGJtfc2JNIaSxMsopffKRrtJd17CbwGc5paeJiH2ESWNlsvLnn0fuXpS2jKHx6NWovLH1J3hyz0iewgw_Q4ZXKcESi5SPC5k1ing_7al3jEoo7E45aFqqFTjuVJs60wM5TPlSaF1dHWyFcm8Y_SMPjcOs8HmHjlS8Rv7UWtPJFrUahyMZPjATcUF51G8NpXDE2pJWUPfl2xQmqZkgkJ4r_gSA8",
    lastUpdate: "2m ago",
    alert: {
      type: "High Risk",
      category: "BP Spike",
      message:
        'Sudden BP spike (150/95) detected via voice analysis. Patient reported "seeing spots".',
    },
    metrics: [{ label: "Heart Rate", value: "115 BPM", trend: "up" }],
    trendData: [50, 45, 48, 40, 35, 38, 25, 20, 15, 10, 5],
  },
  {
    id: "2",
    phone_number: "+254700000003",
    full_name: "Priya Patel",
    name: "Priya Patel",
    due_date: "2026-03-20",
    gestational_week: 36,
    risk_level: "critical",
    language: "en",
    medical_history: { notes: "Gestational diabetes" },
    created_at: "2025-07-10T00:00:00Z",
    date_of_birth: "1990-07-22",
    national_id: null,
    location_address: "Mumbai, India",
    trimester: 3,
    blood_type: "A+",
    previous_pregnancies: 0,
    current_medications: "Insulin",
    allergies: "Penicillin",
    emergency_contact_name: "Raj Patel",
    emergency_contact_relation: "Husband",
    emergency_contact_phone: "+254700000004",
    preferred_checkup_time: "afternoon",
    has_smartphone: true,
    avatarUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCh95iRRavtH6vO_F9a2ks_UaduvZWXRbS3-pn9HsjTt7RNWaD0Ac4bgMhpk0vOmRtLK0ouSwI5WD8lhQxNNiuoXfjJMDsR_cHkOvQk1ViBj_yStsbzGkV_oEoYD9lO5hHZdH9mTljxV8Zs691IFvdFSsH-DALjojxQ32DUFyB8q11QWiX8plCN2bh-2KsMP4sTriDpNGUTU4hduGawYU6MZGTqAifdZFXRGYwAv8LehM1MGUgdzGFeaP9V8Ryr8k5E9ZZoSMEKFWBZ",
    lastUpdate: "45m ago",
    alert: {
      type: "High Risk",
      category: "Preeclampsia Risk",
      message:
        "Severe headache reported with visual disturbances. High probability of preeclampsia onset.",
    },
    metrics: [{ label: "Pain Level", value: "8/10", trend: "up" }],
    trendData: [50, 50, 48, 45, 30, 20, 15, 10, 5],
  },
];

export const mockWarningPatients: DashboardPatient[] = [
  {
    id: "3",
    phone_number: "+254700000005",
    full_name: "Amara Okafor",
    name: "Amara Okafor",
    due_date: "2026-06-10",
    gestational_week: 28,
    risk_level: "high",
    language: "en",
    medical_history: null,
    created_at: "2025-10-01T00:00:00Z",
    date_of_birth: "1995-01-15",
    national_id: null,
    location_address: "Lagos, Nigeria",
    trimester: 3,
    blood_type: "B+",
    previous_pregnancies: 2,
    current_medications: null,
    allergies: null,
    emergency_contact_name: "Chioma Okafor",
    emergency_contact_relation: "Sister",
    emergency_contact_phone: "+254700000006",
    preferred_checkup_time: "morning",
    has_smartphone: true,
    avatarUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCrr2OmyxEYYpd39R10VC2g2BluTHskDpx3dFNpJhg6xfOBm25j3r-lMH_2uvDYhfwgELfA5g7Q77Q-FCBlGcf01W5mfuWhTvHtyvb7OCd1rzTjYOUMiBAW3Lxpoh1vN88jM9nIeaswUaoU9iY_P4Hm4RTBtPVjnqAqK0X1TLWENaehRGISfuFYHt7IPtRLZttdrr644XWmZYC-bT-VlZ-gIjhfwebF57y4yGi2zBg1Gz_JG5B_wgtaBwvv8dSyPSsUbJtcQrNV8dGX",
    lastUpdate: "2h ago",
    alert: {
      type: "Moderate",
      category: "Movement Anomaly",
      message:
        "Reduced fetal movement reported consecutively for 2 days. Deviates from baseline.",
    },
    metrics: [{ label: "Activity Trend", value: "Decreasing", trend: "down" }],
    trendData: [20, 15, 18, 22, 25, 30, 35, 40, 45, 50, 55],
  },
  {
    id: "4",
    phone_number: "+254700000007",
    full_name: "Elena Rodriguez",
    name: "Elena Rodriguez",
    due_date: "2026-04-01",
    gestational_week: 34,
    risk_level: "high",
    language: "es",
    medical_history: { notes: "History of preterm labor" },
    created_at: "2025-08-01T00:00:00Z",
    date_of_birth: "1988-11-30",
    national_id: null,
    location_address: "Mexico City, Mexico",
    trimester: 3,
    blood_type: "AB+",
    previous_pregnancies: 1,
    current_medications: "Progesterone",
    allergies: null,
    emergency_contact_name: "Carlos Rodriguez",
    emergency_contact_relation: "Husband",
    emergency_contact_phone: "+254700000008",
    preferred_checkup_time: "afternoon",
    has_smartphone: true,
    avatarUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCvcpSPrAUDRWPxtw1PsiiuoP_0lsTIMybfpbF439klcZ5u75lGzcrD60nsAcbiNKT8FH1xs8KOcRXZQSU7aBLaDiM4ir5UJsxmiD8Fb5grxu9oznRzsXpyiVBmN_IVhPo66vZuXLAbPXbSDzvNtZjaOyQbuKZM2mZVe_jserlVfU1mbeGchLoITuxb4KW7lV60RjJ3Yg97U1mX4zRe3bcvm2wfNhZ4UoG-o0qAVmfCfwiGRH9Lb57CKw7Ky6Nbq7L6VPzvxrbRmEll",
    lastUpdate: "2d ago",
    alert: {
      type: "Monitor",
      category: "Low Compliance",
      message:
        "Missed check-in for 2 days. Geolocation places patient 50mi from home address.",
    },
    metrics: [{ label: "Compliance", value: "Intermittent", trend: "down" }],
    trendData: [10, 10, 10, 15, 20, 40, 55, 55, 55],
  },
];
